### ISSUE TITLE
How to specify the collection name of mongodb

### ISSUE THREAD

**Issue by toplinuxsir** [numberly/mongo-thingy#13]
If the collection name dose not match the Thingy class name , How to specify the collection name of mongodb?

**Comment by ramnes** [comment]
Hey @toplinuxsir,

You can either specify the collection name: 

```python
class Foo(Thingy):
    collection_name = "bar" 
```

or the collection directly:

```python
class Foo(Thingy):
    collection = db.bar
```

You can then check what collection is being used with:

```python
>>> Foo.collection
Collection(Database(MongoClient('modb-dv-1-p1', 27017), 'database'), 'bar')
```

As you can notice, we really miss a proper documentation, and we're sorry for that. It's our main priority for the upcoming versions.

**Comment by trubesv** [comment]
Documentation for this specific point added in #14

**Comment by ramnes** [comment]
Feel free to open another issue if you have any other question @toplinuxsir. 👍
