### ISSUE TITLE
Changing collection name with `collection_name` attribute

### ISSUE THREAD

**Issue by Shir0kamii** [numberly/mongo-thingy#2]
Currently to change the name of the collection a model uses, you have to set the `table_name` class attribute.

Semantically, it's not very good and it would feel better to use `collection_name`

**Comment by ramnes** [comment]
Do you want to tackle it?

**Comment by Shir0kamii** [comment]
Sure, see #3

**Comment by ramnes** [comment]
Fixed with 7394fd3. Thanks!
