### ISSUE TITLE
Should we drop PyMongo<3.5 support?

### ISSUE THREAD

**Issue by ramnes** [numberly/mongo-thingy#26]
http://api.mongodb.com/python/current/changelog.html#changes-in-version-3-5

Things that are modified in the `pymongo-latest` branch:
* [x] `get_database` rather than `get_default_database`
* [x] That logic with `max_time_ms`: https://github.com/numberly/mongo-thingy/blob/44e54fb306c4d8f6c26bc420dfe34c06f4a60ebf/mongo_thingy/__init__.py#L114-L115
* [x] `Collection.count_documents` instead of `Cursor.count`
* [x] `insert_one`, `replace_one` and `delete_one` instead of `insert`, `update` and `remove`

Fixed on PyMongo 3.5.0: https://github.com/mongodb/mongo-python-driver/commit/7b1cbace17348b71f49277d0edba7615b2da41d7

**Comment by Shir0kamii** [comment]
We made a branch called `pymongo-latest` which uses pymongo 3.7 and get rid of this logic.
