### ISSUE TITLE
How to refresh/ reload data from database?

### ISSUE THREAD

**Issue by Dewsworld** [numberly/mongo-thingy#33]
Hello,

As the title suggests, is there any method for reload?

**Comment by ramnes** [comment]
There isn't, for now! What's your use case?

**Comment by Dewsworld** [comment]
> There isn't, for now! What's your use case?

I want to update the data from the database every 60 secs

**Comment by ramnes** [comment]
For a single object or a cursor?

Why not using `find` or `find_one` again, every 60 seconds?

**Comment by amcgregor** [comment]
"Refreshing" an object does not involve the construction of a new one, and may potentially be limited to a subset (projection) of fields to be refreshed. [Example.](https://github.com/marrow/mongo/blob/develop/marrow/mongo/core/trait/queryable.py?ts=4#L280-L293) (The "TODO" there relates to handling nested/"complex" objects better and the "top level" current limitation.)

Notably, a "refreshed" object will share an identity. (Calling `.reload()` on one handle reloads the object in-place.)

```py
some_record is some_record.reload()
```

Whereas the same is not true of multiply-queried documents. Querying again will potentially leave a hanging reference to the old version of the object.

```py
# With a single record present...
SomeDocument.find_one() is not SomeDocument.find_one()
```

This seems to be the case, here, as well, unless Thingy is doing some fairly deep magic behind-the-scenes to deduplicate and "cache" multiple instances of the underlying data. Something I strongly dislike other DAO engines doing, as it can lead to problems, which can, ironically, involve a greater need for a `reload` method.

**Comment by ramnes** [comment]
I get the identity argument, but I still don't see a use case for a `reload` method. On the opposite, I see a lot of value in supporting change streams, yes!

**Comment by amcgregor** [comment]
I apologize for distracting you from a 15 line fix with a potentially multi-hundred-line one. [Practicality beats purity](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python), but I will gladly accept a differentiating feature between your solution and mine. Change streams and reloading are distinct, and independently useful.

**Comment by ramnes** [comment]
Alright, let's close this issue for now, we're all loosing our time here.
