### ISSUE TITLE
Database discovery isn't documented nor working correctly 

### ISSUE THREAD

**Issue by guilbep** [numberly/mongo-thingy#6]
For instance:

If I have a database sport with a collection synchronised_swimming and I name the class

```python
class SynchronisedSwimming(Thingy):
    collection_name = "synchronised_swimming"
    database_name = "sport"
```

I have to specify the database; if not it will use the synchronised database which does not make sense in that context.

**Comment by ramnes** [comment]
How did you connect? The expected behavior is that Mongo-Thingy will only try to "guess" the database name (based on the class name construct) if it doesn't already have a database registered for that thingy.

**Comment by guilbep** [comment]
The thing is: If I have a class SynchronisedSwimming I want to access the collection 'synchronised_swimming'. But because of the CamelCase the collection used is 'swimming' instead.
even if I say database_name = 'sport'

That's my point the 'guessing' part is not in the documentation.

**Comment by ramnes** [comment]
Please answer my question. If you'd have been connected to a database in the first place, it wouldn't have tried to guess the database, and should have used "synchronisedSwimming" as collection name. If it did not, this is not just documentation problem, but a bug.

**Comment by guilbep** [comment]
Well, looks like it's not the case.

Here what happened:
I first tried 
```python
class SynchronisedSwimming(Thingy):
    pass
```
And it connected to the "synchronised" Database with the "swimming" collection

I then tried 

```python
class SynchronisedSwimming(Thingy):
    database_name = "sport"
```

And it connected to the "sport" Database with the "swimming" collection

I then tried 

```python
class SynchronisedSwimming(Thingy):
    collection_name = "synchronised_swimming"
    database_name = "sport"
```

And it connected to the "sport" Database with the "synchronised_swimming" collection

I thought that when spefifying the database it will not implied the collection name but it is not the case.

I'm using mongo-thingy 0.7.0 by the way.

**Comment by ramnes** [comment]
The second example is definitely a bug.

For the first example, did you use `connect` with a default database (something like `mongodb://domain/database`)?

**Comment by guilbep** [comment]
I think the answer is yes:

@ramnes I used something like
```python
def init():
    config = app.config.get_namespace("MONGO_")
    connect(**config)
```
And I set the env like so:
```raw
env = MONGO_HOST=mongodb://localhost/sport
```

**Comment by ramnes** [comment]
So the first example in your previous comment is a bug too. I guess there some work needed in Thingy too, so I've opened https://github.com/numberly/thingy/issues/6.

**Comment by ramnes** [comment]
Hey @guilbep,

Code is fixed and released; all your examples should work now!

The documentation part will come when we'll have a real one on RTFD.

Thanks for the bug report.
